name: Build Push Changes
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Mod Jar
        run: |
          chmod +x gradlew
          ./gradlew deploy

      - uses: actions/upload-artifact@v2
        with:
          name: CyberIO-Unzip-This
          path: build/tmp/deploy/*.jar

      - uses: actions/setup-python@v4
        if: ${{ contains(github.event.head_commit.message,'[upload]') }}
        with:
          python-version: '3.9'

      - name: Upload Java back-end
        if: ${{ contains(github.event.head_commit.message,'[upload]') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ../
          git clone --depth 1 https://github.com/3Snake3/Sapphirium.git MasterBranch
          python Sapphirium/.github/workflows/upload/back2front.py
          cd MasterBranch
          git config --global user.email "Li_plum@outlook.com"
          git config --global user.name "liplum"
          git add .
          ls -a
          git commit --allow-empty -m "Java back-end update"
          git push https://3Snake3:${{ secrets.SAPP_TOKEN }}@github.com/3Snake3/Sapphirium
